services:
  jellyfin:
    build: . 
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    ports:
      - 8096:8096/tcp
    environment:
      JELLYFIN_CACHE_DIR: /cache
      POSTGRES_HOST: postgres
      POSTGRES_DB: jellyfin
      POSTGRES_PASSWORD: jellyfin
      POSTGRES_USER: jellyfin
    restart: unless-stopped
    user: '1000:1000'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media:ro

  postgres:
    image: postgres:18-alpine
    container_name: postgres-18
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_DB: jellyfin
      POSTGRES_USER: jellyfin
      POSTGRES_PASSWORD: jellyfin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jellyfin -d jellyfin"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./postgres-wal:/var/lib/postgresql-wal
    restart: unless-stopped